### ISSUE TITLE
Can't construct opaque origins from external code

### ISSUE THREAD

**Issue by jdm** [servo/rust-url#144]
There's no public constructor method, and the inner field in OpaqueOrigin is private.

**Comment by SimonSapin** [comment]
We can add a constructor, but where is it useful?

(BTW I’m skeptical that the current behavior of `x.origin() != x.origin()` sometimes is the desired one.)

**Comment by jdm** [comment]
See the "For Document objects" list at https://html.spec.whatwg.org/multipage/browsers.html#origin .

**Comment by pyfisch** [comment]
Why does Origin::OpaqueOrigin even contain a UUID? The [HTML spec](https://html.spec.whatwg.org/multipage/browsers.html#origin) states that opaque identifiers are "Internal values, with no serialisation, for which the only meaningful operation is testing for equality" and that they are not equal with any origin.

```rust
#[test]
fn test_origin_eq() {
    // relative URLs
    let a = Url::parse("http://example.org").unwrap();
    let b = Url::parse("http://mozilla.org").unwrap();
    // everything normal
    assert!(a.origin() != b.origin());
    assert!(a.origin() == a.origin());
    // file urls
    let c = Url::parse("file:///home/user/foobar/Documents/letter.odf").unwrap();
    let d = Url::parse("file:///home/user/foobar/Images/holiday.png").unwrap();
    let c_origin = c.origin();
    // as expected opaque origins are not equal to each other
    assert!(c.origin() != d.origin());
    assert!(c.origin() != c.origin());
    // but if we compare the result from the same origin() they are equal
    assert!(c_origin == c_origin);
    assert!(c_origin == c_origin.clone());
}
```
This is because Rust uses the default implementation of `Eq` which really compares the included UUIDs inside the `Origin`. Since the UUIDs should always be different, even if they are for the same resource rust-url could simply define that any `OpaqueOrigin` is different from any `OpaqueOrigin` in the world including itself without the need to really create UUIDs because we can't look into an `OpaqueOrigin`.

So `Origin` could be defined as:
```rust
/// The origin of the URL
#[derive(Eq, Clone, Debug)]
pub enum Origin {
    /// A globally unique identifier
    Opaque,
    /// Consists of the URL's scheme, host and port
    Tuple(String, Host, u16)
}

impl PartialEq for Origin {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (&Origin::Opaque, _) | (_, &Origin::Opaque) => false,
            (&Origin::Tuple(ref scheme1, ref host1, ref port1),
             &Origin::Tuple(ref scheme2, ref host2, ref port2)) => scheme1 == scheme2
                && host1 == host2 && port1 == port2,
        }
    }
}
```
This avoids a few cycles of computation for the UUID and assures that really never two opaque origins are the same as requested in the spec. And it solves the initial problem of the missing public constructor method.

**Comment by SimonSapin** [comment]
> rust-url could simply define that any OpaqueOrigin is different from any OpaqueOrigin in the world including itself 

It’s not clear to me that "including itself" is the desired behavior.

**Comment by SimonSapin** [comment]
Note that `x.origin() != x.origin()` is not the same as `{ let o = x.origin(); o != o }`

**Comment by pyfisch** [comment]
My proposal does not work. While the [URL standard says about opaque identifiers](https://url.spec.whatwg.org/#origin): "This does indeed mean that these URLs cannot be same-origin with themselves. " and the [linked part of the HTML spec for background information] says "Internal values, with no serialisation, for which the only meaningful operation is testing for equality." there is another [part of the HTML spec](https://html.spec.whatwg.org/multipage/browsers.html#same-origin) says "If A and B are both opaque identifiers, and their value is equal, then return true.". :disappointed: This section also describes a algorithm to compare origins which states that one must compare the value of opaque origins and if the value is the same they are the same. Are origins really passed around inside a browser and then compared?

**Comment by untitaker** [comment]
>Are origins really passed around inside a browser and then compared?

All the time when doing cross-origin requests.
