### ISSUE TITLE
Fails to parse already punycoded emoji

### ISSUE THREAD

**Issue by programble** [servo/rust-url#179]
Parsing an already punycoded emoji in the host fails, while parsing the emoji results in the punycoded host.

``` rust
Url::parse("https://xn--ls8h.cmcenroe.me") // Err(InvalidDomainCharacter)
Url::parse("https://💩.cmcenroe.me") // Ok(Url { scheme: "https", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("xn--ls8h.cmcenroe.me"), port: None, default_port: Some(443), path: [""] }), query: None, fragment: None })
```

**Comment by dagnir** [comment]
The reason seems to be that [`validate`](https://github.com/servo/rust-url/blob/master/src/idna.rs#L188) doesn't like 💩, specifically the `passes_bidi` check.  Something like `Url::parse("http://xn--hckqz9bzb1cyrb.jp")` parses just fine

**Comment by SimonSapin** [comment]
The reason for this difference is that, in [UTS #46 "Processing"](http://www.unicode.org/reports/tr46/#ProcessingStepConvertValidate), domain labels already punycode-encoded (starting with `xn--`) need to meet “Validity Criteria for Nontransitional Processing” while for other labels it is “Validity Criteria for the input Processing choice (Transitional or Nontransitional)”.

The offending line is:

```rust
    || (class == BidiClass::ON && transitional_processing) // starts with \u200D
```

(Commenting it make both test cases return `Err`.)

@valenting, I don’t see anything in https://tools.ietf.org/html/rfc5893#section-2 to support this line. Why is it there? Does Gecko do this?

http://www.unicode.org/reports/tr46/#Right_to_Left_Scripts says
> In addition, the label should meet the requirements for right-to-left characters specified in the Right-to-Left Scripts document of [IDNA2008], and for the CONTEXTJ requirements in the Protocol document of [IDNA2008].

Note the “should”, weaker than “must” used elsewhere. It’s not clear to me whether the error flag should be set in rust-url for labels that don’t meet this “should”.

Following references for CONTEXTJ leads to https://tools.ietf.org/html/rfc5891 and https://tools.ietf.org/html/rfc5892 :
> Some code points need to be allowed in exceptional circumstances but should be excluded in all other cases; these rules are also described in other documents.  The most notable of these are the Join Control characters, U+200D ZERO WIDTH JOINER and U+200C ZERO WIDTH NON-JOINER.  Both of them have the derived property value CONTEXTJ.

I haven’t looked into this further, but it seems relevant since the code comment mentions U+200D. Maybe there is more validity criteria to implement that can replace hacks in `passes_bidi`. Or maybe we should simply drop `passes_bidi`? I’ve filed https://github.com/whatwg/url/issues/110

**Comment by valenting** [comment]
I tried to implement the bidi requirements as close to the standard as possible in order to pass the IDNA unit tests, but I also noticed the browsers are much more relaxed in enforcing bidi rules.
Maybe we could make the bidi check a mere syntax_violation in the 1.0 rust-url instead?

**Comment by SimonSapin** [comment]
If even that. (I don’t think any one actually uses `log_syntax_violation`.) I’d be in favor of simply dropping bidi checks if other browsers don’t implement them, and skip tests with only Bn and Cn error codes.

**Comment by valenting** [comment]
This seems fair. Let me know if you want to do that or if I should.
Thanks!

**Comment by SimonSapin** [comment]
I’ll get to it eventually if you don’t, but this doesn’t seem to be urgent and I’d like to land #176 first :)

**Comment by dtolnay** [comment]
Are we still planning on dropping bidi checks given that other browsers don't implement them? Is anyone already working on it?

**Comment by valenting** [comment]
Since #413 was merged, this test case no longer fails.

**Comment by SimonSapin** [comment]
Closing, feel free to comment if this is still an issue.
