### ISSUE TITLE
advise on upgrading to 1.0 and breaking changes

### ISSUE THREAD

**Issue by softprops** [servo/rust-url#192]
Hi. I'm trying to upgrade my crate for providing a unix domain socket interface for hyper bindings to the latest url release and an running into some difficulties due some some breaking changes in the url crate. I'm looking for some possible advise on how to work around it.

The gist is that I used to rely on the ability to create a [url from its components manually](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L147-L162). In particular I relied on the ability to set a url's [host](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L154) field. 

This allowed me to easily wire together a hyper `NetworkContector` that passes along that [host](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L55) and [stream the io through the unix domain socket](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L58)

My problem is now that I can't create a url from a set of components and I can't seem to create a url with an explicit domain because the default parsing rules now [prevent it](https://github.com/servo/rust-url/blob/master/src/host.rs#L82-L86)

Is there any way to to achieve the same url constructor given the newer api and if not, would you be open to add such an interface to allow me to do so?

**Comment by SimonSapin** [comment]
Short answer: the specification defines that any URL host that is not a literal IP address is a domain, and a `/` character is not legal in a domain. It’s really not designed to handle a filesystem path as a host. Even with a work-around for forbidden characters, domains are normalized trough IDNA (including punycode encoding if there are non-ASCII characters) which is probably undesirable in your case:

https://url.spec.whatwg.org/#host-parsing

----

In 1.0, the `Url` struct does not store URL components as individual fields like before. Instead, there is a single `String` and a few integer indices that tell where things are: https://github.com/servo/rust-url/blob/v1.0.0/src/lib.rs#L158-L183

Since a number of invariants need to be maintained between these fields, they are not public and the only way to get a `Url` value is through the parser. After that you can use the `set_*` methods to change individual URL components, but internally this does string manipulation and typically goes through (part of) the parser. In particular `set_host` will still expect either an IP address or a domain which is normalized by IDNA and where some characters (including `/`) are rejected.

I think your issue is not creating a `Url` from components. It’s rather that the host component can not contain a filesystem path, same as in https://github.com/servo/rust-url/issues/26

**Comment by SimonSapin** [comment]
@seanmonstar What do you think? Is there a better way to deal with Unix sockets than trying using an URL’s host as a filename?

**Comment by nox** [comment]
In HTTP/1.1 you are always supposed to pass a host to the server, be that through the URL itself after the HTTP method at the very beginning of the request, or through the Host header. How does that work through a UNIX socket?

@seanmonstar Do you think we could separate the notion of transport from the actual URLs? That sounds like a more robust way than cramming things inside the request URL.

**Comment by seanmonstar** [comment]
@nox: HTTP/1.1 [requires sending a `Host` header no matter what](https://tools.ietf.org/html/rfc7230#section-5.4).

In the async branch, I think I'm settling on passing a `&Url` to `connect`, instead of breaking it into parts. That HTTP only needs the scheme, host, and port makes it prejudiced against other connecting schemes.

In this case, could the `UnixSocketConnector` do something like DNS, and use a sort of domain name, and the connector can map that to a file path and use that to create the stream?

**Comment by softprops** [comment]
> How does that work through a UNIX socket?

Sleight of hand.

I relied/exploited to the ability to [set the url host explicitly](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L154) which hyper hands off to a [network connector](https://github.com/softprops/hyperlocal/blob/master/src/lib.rs#L55) which I then use to create a unix socket stream

**Comment by softprops** [comment]
> In the async branch, I think I'm settling on passing a &Url to connect, instead of breaking it into parts. That HTTP only needs the scheme, host, and port makes it prejudiced against other connecting schemes.

> In this case, could the UnixSocketConnector do something like DNS, and use a sort of domain name, and the connector can map that to a file path and use that to create the stream?

It's just a path to a file on the current host. I think the interface you're proposing will actually make things more straight forward for me @seanmonstar

**Comment by seanmonstar** [comment]
@softprops To clarify what I meant, for 0.9.x, could you hex-encode the socket path, and use that as the hostname?

```rust
let hostname = b"/path/to/socket".hex_encode();
client.get(format!("unix://{}/{}", hostname, path))

fn connect(&self, host: &str, port: u16, scheme: &str) {
    let path = try!(host.as_bytes().hex_decode());
    assert_eq!(b"/path/to/socket", path)
}
```

**Comment by softprops** [comment]
oh @seanmonstar sweet! I'll try that out tonight

**Comment by softprops** [comment]
going to go and close this issue then as it's not really an issue with this crate and the advise given was terrific

**Comment by softprops** [comment]
@seanmonstar that worked like a charm. many thanks
