### ISSUE TITLE
Does not build with rustc 1.6.0 and cargo 0.8.0

### ISSUE THREAD

**Issue by matthiasbeyer** [servo/rust-url#213]
According to https://github.com/matthiasbeyer/imag/issues/515 this crate does not build on

* rustc: 1.6.0
* cargo: 0.8.0

which is shipped with NixOS stable release. Error output is in the issue mentioned above. I hope this can be fixed.

**Comment by SimonSapin** [comment]
Is the error message says, rust-url uses the `std::net::IpAddr` type which was marked as unstable and therefore could not be used in Rust 1.6.

It should be *possible* to add a Cargo "feature" to rust-url that’s enabled by default, and have the `Url::set_ip_host` method only exist when that feature is enabled. I don’t know how Cargo deals with `no_default_features` for transitive dependencies, though.

However, I don’t really *want* to be stuck supporting old compiler versions. Rust and its standard library are still young, and they will likely gain more features that we might want to use in rust-url.

How often is NixOS updated? Is there a strong reason to get a compiler from NixOS rather than, for example, rustup.rs?

**Comment by matthiasbeyer** [comment]
@SimonSapin thanks for your quick reply. I filed an issue to update rustc and cargo on the stable channel for nixos... I'm not sure how fast it will be updated (if it will be updated), as I'm using the unstable release.

I see that you don't want to maintain old compiler versions (completely sane to me, no objections).

I will see whether I can get the NixOS guys to update rustc and cargo, then. Feel free to close this issue therefor.

**Comment by SimonSapin** [comment]
FWIW I just looked it up and 1.6 was released on 2016-01-21. Which is not that old in the grand scheme of things, but it’s almost half the age of 1.0.

Closing, but feel free to discuss more.
