### ISSUE TITLE
Allow optional exclude fragment flag for URL serialization

### ISSUE THREAD

**Issue by malisas** [servo/rust-url#221]
From [step 7](https://url.spec.whatwg.org/#url-serializing):
> If the exclude fragment flag is unset and url’s fragment is non-null, append "#", followed by url’s fragment, to output.

Currently the fragment is always included in the serialized form.
Thanks!

**Comment by SimonSapin** [comment]
In the 1.0 redesign, rust-url got a more general mechanism with indexing and [the `Position` enum](https://servo.github.io/rust-url/url/enum.Position.html). You can use something like:

```rust
fn serialize_without_fragment(url: &url::Url) -> &str {
    &url[..url::Position::AfterQuery]
}
```

This is less discoverable than a dedicated method, but I’d prefer to add better docs for it rather than lots of one-off methods (like "protocol and host and port", "host and port", "path and query", …)

**Comment by malisas** [comment]
Thank you!
