### ISSUE TITLE
Incorrectly (?) parses `http:example.com` without slashes after scheme

### ISSUE THREAD

**Issue by callahad** [servo/rust-url#235]
This surprised me, and I'm not sure if it's correct behavior or not. Both assertions fail, where I would've expected `http:example.com` to be parsed into an OpaqueOrigin.

```rust
extern crate url;

#[cfg(test)]
mod tests {
    use super::url::Url;

    #[test]
    fn it_works() {
        let a = Url::parse("http://example.com").unwrap();
        let b = Url::parse("http:example.com").unwrap();

        assert!(a.as_str() != b.as_str());
        assert!(a.origin() != b.origin());
    }
}
```

For comparison, Python 3 shows expected behavior:

```python
>>> from urllib.parse import urlparse
>>> urlparse("http://example.com")
ParseResult(scheme='http', netloc='example.com', path='', params='', query='', fragment='')
>>> urlparse("http:example.com")
ParseResult(scheme='http', netloc='', path='example.com', params='', query='', fragment='')
```

**Comment by SimonSapin** [comment]
I believe this is the correct behavior according to the parsing algorithm specified at https://url.spec.whatwg.org/#url-parsing. Specifically, `http` is one of the few so-called "[special](https://url.spec.whatwg.org/#special-scheme)" schemes that get a different treatment. It also matches what browsers do (I just tried Chrome and Firefox), try entering this in the address bar:

```
data:text/html,<a href=http:example.com><script>document.write(document.getElementsByTagName('a')[0].href)</script>
```

Since the original goal of this library is to be used in Servo, I care more about matching other browsers than matching Python (which as far as I know isn’t trying to achieve interoperability on this with anything else).
