### ISSUE TITLE
Update for serde 0.9.0

### ISSUE THREAD

**Issue by indiv0** [servo/rust-url#277]
Would it be possible to bump the serde version in the Cargo.toml to support serde 0.9.0?

**Comment by SimonSapin** [comment]
The problem is that that would be a breaking change, we’d need to change the `url` version number to 2.0.0. Since (for example) Hyper uses `url::Url` is some of its public APIs, updating it to url 2.0.0 would also be a breaking change and Hyper’s own version number would need to be changed accordingly. Since url [is used a lot](https://crates.io/crates/url/reverse_dependencies), this cascading effect is pretty disruptive overall. Maybe you were involved [when the `libc` crate went from 0.1 to 0.2](https://github.com/servo/servo/issues/8608)?

For this reason, the plan is to replace the serde support in `url` itself by the `url_serde` crate: https://docs.rs/url_serde/ This one already uses 0.9.

**Comment by indiv0** [comment]
Ah. That makes sense. Thank you for the link :)
