### ISSUE TITLE
Implement `ToOwned` instead of having a custom `to_owned` method

### ISSUE THREAD

**Issue by clarcharr** [servo/rust-url#286]

**Comment by clarcharr** [comment]
Additionally, `parse` methods should go into `FromStr` impls.

**Comment by SimonSapin** [comment]
I don’t really care, so I’m not gonna implement this myself. If someone wants to send a PR I’ll take it.

**Comment by clarcharr** [comment]
@SimonSapin I will do that in a bit. I think that it doesn't make sense to close an issue like this if it's desired but not prioritised; it's a decent first bug for someone who wants to submit a PR.

**Comment by SimonSapin** [comment]
> if it's desired

It’s not. I don’t see the point. I’m only not opposed to it enough to reject a PR if someone else wants it enough to make a PR.

**Comment by SimonSapin** [comment]
I see that this is linked from an issue on Clippy, which tends to be very opinionated.

I’d be much less sympathetic accepting code that I’ll need to maintain if it’s based purely on an opinion of how things should be in principle, rather than on someone’s concrete use case who will then actually use that code.

**Comment by clarcharr** [comment]
A very simple use case is storing `Host`s as `HashMap` keys; because `Host<String>` would implement `Borrow<Host<&str>>`, you could request to get `Host::Domain("localhost")` in a map that stores owned copies.

As far as the actual `ToOwned` implementation goes, it's not necessarily *required* but the amount of effort is really in the conversion, not actually having a `ToOwned` implementation itself. The real bulk come from the `Borrow` that comes with it.

It does have feasible use cases, but I figured I'd just open an issue now because I'm focused on something else at the moment and didn't want to forget about it. I'll offer a PR tomorrow. :)

**Comment by SimonSapin** [comment]
Ah, mentioning `HashMap` is already a much better motivation than “because Clippy said so”. But does anyone ever use `Host` in hash map key, or is that a theoretical use case that was made up in a search of why `ToOwned` might be useful?

To some extent, the only reason I created the `Host` type is to carry the return value of `Url::host`. If the standard library had a generic `Either` enum I’d have used that.
