### ISSUE TITLE
Modify examples to not call `unwrap`

### ISSUE THREAD

**Issue by brson** [servo/rust-url#312]
Several examples in `url` call `unwrap`. It's preferable to use `?` to avoid teaching bad practices to new Rust coders. Modify the examples to have some hidden scaffolding to set up the `Result` type and use `?` instead.

**Comment by luisbg** [comment]
This looks like a fun way to read example code, and help with cleanup.

I can work on this if nobody else is.

**Comment by luisbg** [comment]
Since the code examples are by default wrapped in a `fn main() {`, a direct switch to using ? will have the example fail in cargo test because () is expected instead of the Result the ? returns.

The way around it is to add a fn foo() -> Result<> { around the example, but this means making the examples a bit bigger than they should be.

Confirming here what is the approach you want to take.

Going to send a WIP patch to clarify what I mean. Let me know what you think.

**Comment by luisbg** [comment]
I am looking at this again. Will report soon. Sorry for the delay.

**Comment by luisbg** [comment]
Nice! Thanks @Enet4 😄
