### ISSUE TITLE
URL Parsing for Databases and other things

### ISSUE THREAD

**Issue by mitsuhiko** [servo/rust-url#40]
At the moment if you want to parse a URL in the format `databasedriver://hostname:port/whatever` you need to write your own scheme handler function.  It's not super annoying but it's definitely something people might miss when they expect this thing to parse them a hostname.

Since nobody does URL joining anyways would it make sense to introduce an interface that provides a parser that is RelativeScheme with a dummy port for all schemes by default?

**Comment by ivanceras** [comment]
+1 for this,
I need to be able to parse database url
```rust
let parsed = Url::parse(
        "postgres://postgres:p0stgr3s@localhost/bazaar_v6"
    ).unwrap();
    println!("postgres: {:?}", parsed);
    
    assert!( parsed == Url { 
             scheme: "postgres".to_string(), 
             query: None,
             fragment: None,
             scheme_data: Relative(
                 RelativeSchemeData { 
                     username: "postgres".to_string(), 
                     password: Some("p0stgr3s".to_string()), 
                     host: Domain("localhost".to_string()), 
                     port: None, 
                     default_port: Some(5432), 
                     path: vec!["bazaar_v6".to_string()] 
                 })
             });
```

**Comment by Manishearth** [comment]
We could have a cargo feature that defaults unknown scheme to a regular scheme

**Comment by ivanceras** [comment]
@Manishearth  which feature, do you have a link to it?

**Comment by Manishearth** [comment]
No, I mean that we can use [Cargo Features](http://doc.crates.io/manifest.html#the-[features]-section) to allow users of this library to select a flavor that handles unknown schemes.

**Comment by SimonSapin** [comment]
@ivanceras, have you seen [`UrlParser::scheme_type_mapper`](https://servo.github.io/rust-url/url/struct.UrlParser.html#method.scheme_type_mapper)? Manish is talking about potential changes to rust-url that don’t exist yet, to make his more convenient.

Also, the spec changed recently so that relative schemes are the default. I need to look into that to see how that should affect the rust-url API:

https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jun/0028.html
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27233

**Comment by SimonSapin** [comment]
I believe 1.0 (to be published today) fixes this. "Scheme type mappers" are gone and `Url::parse("postgres://postgres:p0stgr3s@localhost/bazaar_v6")` does what you’d expect.

More precisely:

* URL strings with `://` (colon double slash) after the scheme/protocol are parsed with an "authority" (username, password, host, port) in addition to the scheme, path, query, and fragment.
* Those with `:/` (colon single slash) are parsed without an authority. Just scheme, path, query, and fragment. For example: `postgres:/var/run/pg.socket?database=foo`
* Those with neither (typical of `data:` or `mailto:`, for example) are parsed without an authority and the "path" (not really a path) is an arbitrary string instead of a slash-separated list of path segments.

(This is the spec change mentioned above.)
