### ISSUE TITLE
url::percent_encoding does not encode the plus sign '+'?

### ISSUE THREAD

**Issue by najamelan** [servo/rust-url#416]
I tried using percent_encoding, but it doesn't seem to encode the plus sign. Firefox interprets this as a space character, at least in query strings.

**Comment by SimonSapin** [comment]
https://url.spec.whatwg.org/#urlencoded-parsing specifies that that a plus sign is encoded to itself, and decoded to space. This indeed looks like a bug. Could you file it at https://github.com/whatwg/url/issues/ please?

**Comment by najamelan** [comment]
https://url.spec.whatwg.org/#urlencoded-serializing says:
```
Otherwise

    Append byte, percent encoded, to output.
```
Since the plus '+' character is not present in any of the previous classes, it should be considered to fall into the "Otherwise" default encoding. This clearly specifies that it should be percent encoded. The 'url' crate passes it through without encoding it, which is particularly unfortunate because the plus '+' character has a special meaning in an encoded string, namely it represents a space character. 

To resume:
- encode space to plus; decode plus to space
- encode plus to %2B; decode %2B to plus

The following code proves the bug:

```rust
extern crate url;

use url::percent_encoding::{ percent_encode, percent_decode, QUERY_ENCODE_SET};

fn main()
{
   assert_eq!(                      &percent_encode( b"+"  , QUERY_ENCODE_SET ).collect::<String>()            , "%2B" );
   assert_eq!(                      &percent_encode( b" "  , QUERY_ENCODE_SET ).collect::<String>()            , "+"   );
   assert_eq!( std::str::from_utf8( &percent_decode( b"+"                     ).collect::<Vec<u8>>() ).unwrap(), " "   );
   assert_eq!( std::str::from_utf8( &percent_decode( b"%2B"                   ).collect::<Vec<u8>>() ).unwrap(), "+"   );
}
```
Output:
```
   Compiling plus v0.1.0 (file:///tmp/plus)
    Finished dev [unoptimized + debuginfo] target(s) in 0.58 secs
     Running `target/debug/plus`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"+"`,
 right: `"%2B"`', src/main.rs:7:3
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by SimonSapin** [comment]
You’re right, I misread the spec, it does say to percent-encode `+` in the "application/x-www-form-urlencoded byte serializer".

And the implementation of that algorithm in `url::form_urlencoded` does too. I also misread your issue (sorry) and assumed it was about form-urlencoded since you mentioned the plus sign. But the plus sign is only special in form-urlencoded (replaced with spaces in the "application/x-www-form-urlencoded parser"), not in percent-encoding as specified at https://url.spec.whatwg.org/#percent-decode.

If you want to encode key/value pairs as form-urlencoded, you should use `some_url.query_pairs_mut()` or `let mut string = String::new(); url::form_urlencoded::Serializer::new(&mut string)`:

https://docs.rs/url/1.6.0/url/form_urlencoded/struct.Serializer.html

**Comment by najamelan** [comment]
Ok, 
thanks for clarifying that. My bad for choosing the wrong algorithm. That being said I find the docs a bit sparse, they  might benefit from a few examples to show the usage of the different methods. I will close this issue.

**Comment by najamelan** [comment]
Sorry for my last comment, I see now the main api is on the Url struct, which has examples. I think I ended up on the percent_encoding in the docs because I must have searched for "rust percent encoding" in a search engine. I kind of came in through the back door.
