### ISSUE TITLE
Expose parse method to parse hostname:port

### ISSUE THREAD

**Issue by seanmonstar** [servo/rust-url#42]
My use case: the `Host` http header.

I'm parsing into a `struct Host { hostname: String, port: Option<Port> }`.

**Comment by SimonSapin** [comment]
I’m not sure this exact functionality belongs in this crate, since there may be many variations of kind-URL-like things that people might want to parse.

My recommendation is to use this regexp or some equivalent hand-written parser: `^(.*?)(:\d+)?$` (where `*?` is non-greedy repetition), then `url::Host::parse` (which deals with IP addresses and IDNA).

**Comment by clarcharr** [comment]
Perhaps `HostAndPort` could implement `FromStr`?

**Comment by SimonSapin** [comment]
I don’t have much to add beyond my previous response. The question is not what the API would look like, but what the exact behavior be and what is in scope for this crate. I think this is not in scope.
