### ISSUE TITLE
Cannot figure out how to use cannot_be_a_base()

### ISSUE THREAD

**Issue by crusty-dave** [servo/rust-url#456]
I want to be able to parse just the query portion of a URI, however, I get the error **RelativeUrlWithoutBase** if I don't include the "http://host/" base.

Furthermore, the following example doesn't build:

```
extern crate url;

use url::{Url, Host};

fn main() {
    let issue_list_url = Url::parse(
        "https://github.com/rust-lang/rust/issues?labels=E-easy&state=open"
    )?;

    assert!(issue_list_url.scheme() == "https");
    assert!(issue_list_url.username() == "");
    assert!(issue_list_url.password() == None);
    assert!(issue_list_url.host_str() == Some("github.com"));
    assert!(issue_list_url.host() == Some(Host::Domain("github.com")));
    assert!(issue_list_url.port() == None);
    assert!(issue_list_url.path() == "/rust-lang/rust/issues");
    assert!(issue_list_url.path_segments().map(|c| c.collect::<Vec<_>>()) ==
        Some(vec!["rust-lang", "rust", "issues"]));
    assert!(issue_list_url.query() == Some("labels=E-easy&state=open"));
    assert!(issue_list_url.fragment() == None);
    assert!(!issue_list_url.cannot_be_a_base());
}

```

> error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
>  --> src\main.rs:6:26
>   |
> 6 |       let issue_list_url = Url::parse(
>   |  __________________________^
> 7 | |         "https://github.com/rust-lang/rust/issues?labels=E-easy&state=open"
> 8 | |     )?;
>   | |______^ cannot use the `?` operator in a function that returns `()`
>   |
>   = help: the trait `std::ops::Try` is not implemented for `()`
>   = note: required by `std::ops::Try::from_error`
> 
> error: aborting due to previous error
> 

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `uri-test`.

That came from here:
https://docs.rs/url/1.7.1/url/

It seems I need the "**?**" **Try** syntax to use **Url::cannot_be_a_base()**.  I don't understand why you wouldn't just make that an option on the **Url** so that it wouldn't return an error result.

**Comment by crusty-dave** [comment]
Full build log:

>    Compiling matches v0.1.7
>    Compiling unicode-normalization v0.1.7
>    Compiling percent-encoding v1.0.1
>    Compiling unicode-bidi v0.3.4
>    Compiling idna v0.1.5
>    Compiling url v1.7.1
>    Compiling uri-test v0.1.0 (uri-test)
> error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
>  --> src\main.rs:6:26
>   |
> 6 |       let issue_list_url = Url::parse(
>   |  __________________________^
> 7 | |         "https://github.com/rust-lang/rust/issues?labels=E-easy&state=open"
> 8 | |     )?;
>   | |______^ cannot use the `?` operator in a function that returns `()`
>   |
>   = help: the trait `std::ops::Try` is not implemented for `()`
>   = note: required by `std::ops::Try::from_error`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0277`.
> error: Could not compile `uri-test`.
> 
> To learn more, run the command again with --verbose.
>

**Comment by crusty-dave** [comment]
This is building on Windows 10, in case that matters.

**Comment by crusty-dave** [comment]
Note that the 2nd example also fails the same way:

`extern crate url;

use url::{Url};

fn main() {
    let data_url = Url::parse("data:text/plain,Hello?World#")?;

    assert!(data_url.cannot_be_a_base());
    assert!(data_url.scheme() == "data");
    assert!(data_url.path() == "text/plain,Hello");
    assert!(data_url.path_segments().is_none());
    assert!(data_url.query() == Some("World"));
    assert!(data_url.fragment() == Some(""));
}
`

> cargo -vv build
>        Fresh matches v0.1.7
>        Fresh unicode-normalization v0.1.7
>        Fresh percent-encoding v1.0.1
>        Fresh unicode-bidi v0.3.4
>        Fresh idna v0.1.5
>        Fresh url v1.7.1
>    Compiling uri-test v0.1.0 (file:uri-test)
>      Running `rustc --crate-name uri_test src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=105d65b223853b5f -C extra-filename=-105d65b223853b5f --out-dir testing\uri-test\target\debug\deps -C incremental=testing\uri-test\target\debug\incremental -L dependency=testing\uri-test\target\debug\deps --extern url=testing\uri-test\target\debug\deps\liburl-990753c4b9237ac9.rlib`
> error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
>  --> src\main.rs:6:20
>   |
> 6 |     let data_url = Url::parse("data:text/plain,Hello?World#")?;
>   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
>   |
>   = help: the trait `std::ops::Try` is not implemented for `()`
>   = note: required by `std::ops::Try::from_error`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0277`.
> error: Could not compile `uri-test`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name uri_test src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=105d65b223853b5f -C extra-filename=-105d65b223853b5f --out-dir testing\uri-test\target\debug\deps -C incremental=testing\uri-test\target\debug\incremental -L dependency=testing\uri-test\target\debug\deps --extern url=testing\uri-test\target\debug\deps\liburl-990753c4b9237ac9.rlib` (exit code: 101)
>

**Comment by SimonSapin** [comment]
Ok, there are a few different things going on here.

First some background: an URL like `../foo?bar=baz` is said to be *relative*, because its full interpretation depends on "where" it used. Relative URLs are resolved based on a *base* URL. When an HTML document contains for example `<a href="../foo">`, the base URL is typically the URL of that document. Moving the same HTML code to a different document might change the meaning of the URL. Resolving `../foo?bar=baz` with the base `https://example.com/a/b/c?d` produces `https://example.com/a/foo?bar=baz`.

On the contrary, an URL is said to be *absolute* when it is fully determined, regardless of what is used as a base. For example `https://github.com/servo/rust-url` is absolute. The `Url` type always represents an absolute URL. However it can parse relative URLs when you also provide a base URL.

Now:

* The title mentions the `cannot_be_a_base` method. You probably don’t need to use it.

* The `RelativeUrlWithoutBase` error occurs, well, when you try to parse a relative URL without providing a base URL. `Url::parse("…")` parses without a base. To provide a base, use `base_url.join("…")` instead, where `base_url` is itself a value of the type `Url` (which might itself have been parsed with `Url::parse` for example).

* The `` the ? operator can only be used in a function that returns Result or Option (or another type that implements std::ops::Try)`` error also explains when it is about. The point of the `?` operator is to propagate errors to the caller of the current function. However the return type of your `main` function cannot express an error because it is `()` a.k.a. the empty tuple a.k.a. the unit type. (A function "not having" a return type is the same as the return type being `()`.) You can read more about error handling in Rust and the `Result` type and the `?` operator here: https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html

  For quick experimentation where you don’t care about error handling, you can use the `.unwrap()` method instead of the `?` operator. This returns the value if there is one, or panics (causes the program to stop) if there is an error.

  In recent versions of Rust you also can change the `main()` function to return a `Result`. (Returning an error causes the error to be printed and the program to exit with an error code.) This enables using the `?` operator directly inside `main`.

```rust
fn main() -> Result<(), Box<std::error::Error>> {
    let url = Url::parse("…")?;
    // ...
    Ok(())
}
```

**Comment by crusty-dave** [comment]
The example should be changed to use ".unwrap()" instead of "?".

**Comment by dekellum** [comment]
API guidelines and community direction suggests going the other way, meaning: removing `unwrap()` from all doctest examples and replacing with `?`

**Comment by crusty-dave** [comment]
In that case the example should be modified so that it will build, include it in main() defined in a way that it will build.

**Comment by dekellum** [comment]
Apologies if this seems obtuse or insensitive, @crusty-dave, but the current rust doctest [example](https://docs.rs/url/1/url/) is as per guidelines (and community direction) and *is tested* via `cargo test`. Readers of the (linked) rustdoc can view source if they want to see the doctest framing which is compatible, since it converts via `unwrap()`, with rustc >= 1.17.0 main, which is the MSRV encoded in this projects (travis.yml) per community convention.  

As unaffiliated 3rd party user, I will now shut up. :=)

**Comment by crusty-dave** [comment]
@dekellum I still have a lot to learn, I appreciate your taking the time to explain it.

**Comment by SimonSapin** [comment]
If you want to decode a list of key/value pairs in `application/x-www-form-urlencoded` (like in URL queries) without a full URL, consider using the [`url::form_urlencoded`](https://docs.rs/url/1.7.1/url/form_urlencoded/index.html) module.

As @dekellum pointed out, it is by choice that the examples in documentation do not show all the boilerplate that is necessary to get something to compile. The docs of a particular library assume do assume some knowledge of the language. This may indeed be a barrier to newcomers, but it’s a trade-off. In this case though the compiler’s error message is accurate, and googling it gives a number of resources that can help fix it.

I’ll mark this as closed now since there doesn’t seem to be a bug to fix in rust-url, but feel free to keep discussing.

**Comment by crusty-dave** [comment]
Simon,

Thank you very much, that is almost exactly what I wanted.  It seems I just need to manually step over the start of the query to point to the pairs.

```
        let query_url: &[u8];
        let pos_result = uri.find('?');
        let _m = match pos_result {
            Some(pos) => {
                query_url = uri.split_at(pos+1).1.as_bytes();
            }
            None => {
                query_url = uri.as_bytes();
            }
        };

        let query_parse = form_urlencoded::parse(query_url);

        println!("query_url {:?}", query_url);
        println!("pairs count {:?}", query_parse.count());

        for one_pair in query_parse {
            let tag = one_pair.0.to_string();
            let value = one_pair.1.to_string();
            println!("pair {:?}", one_pair);
            println!("tag {}, value <{}>", tag, value);
        }
```

Thanks again,
-Dave
