### ISSUE TITLE
Semantic URL equality

### ISSUE THREAD

**Issue by NeoLegends** [servo/rust-url#458]
This test

```rust
#[test]
fn query_params_eq() {
    let url1 = Url::parse("https://example.com/").unwrap();
    let mut url2 = Url::parse("https://example.com/?test=bla").unwrap();
    url2.query_pairs_mut().clear();

    assert_eq!(url1, url2);
}
```

fails like this:

```
failures:

---- sanitize::tests::query_params_eq stdout ----
thread 'sanitize::tests::query_params_eq' panicked at 'assertion failed: `(left == right)`
  left: `"https://example.com/"`,
 right: `"https://example.com/?"`', src/sanitize.rs:80:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

because `url2` has a trailing `?`while `url1` does not.  AFAIK these two URLs have no difference in meaning - yet they don't equal. I raise the question whether it makes sense to test URLs for equality by their semantics instead of their serialization.

**Comment by SimonSapin** [comment]
As discussed in https://tools.ietf.org/html/rfc3986#section-6 and https://github.com/servo/rust-url/issues/451 "semantic equivalence" is a fuzzy concept. There are many aspects of URLs that you could choose to normalize or not. The WHATWG URL Standard makes a set of choices in https://url.spec.whatwg.org/#url-equivalence and its other algorithms, and rust-url implements that.

What is the issue you’re trying to solve? Why is it a problem that those specific URLs do not compare equal?

Note that you can also do `url2.set_query(None)` to make an URL have no query component at all, rather than a query that is the empty string.

**Comment by SimonSapin** [comment]
> What is the issue you’re trying to solve? Why is it a problem that those specific URLs do not compare equal?

Closing for lack of response, but feel to comment further.
