### ISSUE TITLE
Can't join string containing a colon character

### ISSUE THREAD

**Issue by bbigras** [servo/rust-url#475]
With the colon character the result is `"values:batchGet"`. If I remove the colon character the join works.

I have no idea if colon is allowed in the http specs.

This is to use google's api: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet

```rust
extern crate url; // 1.7.2

fn main() {
    use url::Url;

    let mut url = Url::parse("https://sheets.googleapis.com/v4/spreadsheets/")
        .unwrap()
        .join("values:batchGet")
        .unwrap();

    println!("url: {:?}", url.as_str());
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=80efbd2e5f475c33bf4d5158a7741de7

**Comment by SimonSapin** [comment]
`a.join(b)` means "parse b as a URL, using a as the base URL to resolve relative URLs". In this example, the base URL is ignored because the input string looks like an absolute URL in the `values:` scheme/protocol, similar to what you would get with `<a href="values:batchGet">`. If you want to force an URL string to be path-relative, consider starting it with `./`. If you want to append a single path component to an URL (not parse a new URL with a base), try `url.path_segments_mut().unwrap().push("foo");`.

**Comment by bbigras** [comment]
Thanks.
