### ISSUE TITLE
Relative URLs with unknown base

### ISSUE THREAD

**Issue by rictic** [servo/rust-url#487]
I'm writing some code that transforms source code, specifically URL strings in HTML, CSS,  and JS. These URLs may be relative (e.g. `./foo.js`, `/bar.css`, `../search?query=cats`) and my code won't have the context of the base URL that these URLs would be interpreted relative to at runtime.

I didn't see any public API that supports parsing or providing structured handling of this sort of URL. Is it a use case you'd be interested in supporting?

**Comment by SimonSapin** [comment]
I think I would call this outside of the scope of this crate. The `Url` type always represents an absolute URL.

What transformation do you need to do on those URL strings?

**Comment by rictic** [comment]
The main operation I need right now is to resolve a url from a base. e.g. if we encountered the url `./foo.js` inside `./public/docs.html` I'd want to produce the URL `./public/foo.js`. This is specifically for prototyping build-time tooling around [the WIP import maps spec](https://github.com/WICG/import-maps).

Correctly handling absolute URLs, absolute paths, query params and hashes, not to mention encoding makes for a decent amount of code and a lot of overlap with other url handling.

**Comment by SimonSapin** [comment]
In terms of implementation I expect that dealing with `..` path segments without a base URL is just different enough from with one that I expect that supporting either in the same code base would be non-trivial.

In terms of public API, I expect this new feature would be entirely separate from what’s already in the `url` crate. (The `Url` type would not be involved.)

For these reasons I think this would be better in a separate crate. Feel free to copy some of the code according to the license, though.

**Comment by KiChjang** [comment]
To me, this issue sounds like a confusion between URLs and URIs. My understanding is that the use case that @rictic described pertains to URIs, because they are relative paths without a base at compile-time. IIRC, URLs are explicitly required to have absolute paths.
Given the above, I'd suggest the author to look into using the http crate for URI parsing. See https://github.com/hyperium/http/issues/73 for more information about the history behind http not including the url crate as one of its components, in particular [this comment from @SimonSapin](https://github.com/hyperium/http/issues/73#issuecomment-422960249)

**Comment by SimonSapin** [comment]
I don’t believe that’s what the difference between URL and URI is. But I also don’t believe that distinction is useful at all, or relevant here.

**Comment by rictic** [comment]
Seems reasonable, thanks!
