### ISSUE TITLE
Method to return path + query

### ISSUE THREAD

**Issue by djmitche** [servo/rust-url#492]
In many cases it's useful to capture everything after the host/port -- the path, query, and possibly fragment.  Currently, that can be done by doing some fancy conditionals with `url.path()`, `url.query()`, and `url.fragment()`, but it's tricky and requires allocation.  Really, what I want is `serialization[path_start..fragment_start]` and the like.  So, two questions.

1. Would this be accepted?
2. What would the methods be named?  I don't have better ideas than `path_and_query()` and `path_query_and_fragment()`.

**Comment by SimonSapin** [comment]
This could definitely be more discoverable in docs, but `Url` implements the `Index` trait with ranges of [the `url::Position` enum](https://docs.rs/url/1.7.2/url/enum.Position.html). For example:

```rust
use url::Position;
let a = url[Position::BeforePath..];
let b = url[Position::BeforePath..Position::AfterQuery];
```

Both `a` and `b` have type `&str`. (Using `BeforeFragment` instead of `AfterQuery` would include the `#` separator when there is one.)

This scheme allows for arbitrary combinations of start and end points, without having to come up for a name for each of them.

**Comment by djmitche** [comment]
That is very cool!  I'll see if I can't make a PR to improve discoverability.
