### ISSUE TITLE
I think host parsing is incorrect, might not follow spec, use ASCII / IDNA only

### ISSUE THREAD

**Issue by timvisee** [servo/rust-url#554]
A few days ago I discovered that some string are parsed successfully as `Url`, even though I'm quite certain those are invalid, such as `"http://\""`. (see https://github.com/seanmonstar/reqwest/issues/668 via #552)

### The problem
I located the problem to be with hostname parsing. Any hostname characters are accepted at this moment (except for a small blacklist). I believe hostnames must be limited to ASCII or IDNA encodable characters, so that'd be an error.

To fix this, I changed the following line to use `domain_to_ascii_strict` instead.
This strict variant fails on any character that is not encodable as ASCII/IDNA:

https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/src/host.rs#L83

Changing this does solve the issue I've linked before: https://github.com/seanmonstar/reqwest/issues/668

### The catch
But there's a catch. This change makes a few included unit tests fail. I'm
wondering whether these unit tests are conform the [URL specification][url-spec] that is explicitly linked in the README of this crate. If these are not, I'd argue they should be fixed or removed.

#### Failing tests
* First, the 'Domains with empty labels' fails from the test data set:
  https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/tests/urltestdata.json#L3802-L3847
  This is probably related to the following:

* Second, the leading dots (host) unit test fails:
  https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/tests/unit.rs#L421-L429  
  Issue #166 and #337 are related.

* Third, the host unit test fails:
  https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/tests/unit.rs#L203-L237  
  Only line [219](https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/tests/unit.rs#L219) and [234](https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/tests/unit.rs#L234) fail. Has to do with dots again.

I don't know whether these tests are conform the URL specification. Sadly, I don't have enough time right now to study this.

### Questions
Now I might be totally wrong on this, that's why I'm asking the following to `url` maintainers. Hopefully you can help me out.

- Is my assumption correct, is `"http://\""` incorrect?
- Should `Url::parse(...)` fail, for input not conform the [URL specification][url-spec]?
- Should hostnames be limited to ASCII and IDNA characters?
- Are the linked unit tests faulty, based on the above?

Based on the questions above, what would be the proper steps to take, if there are any?
Maybe a special case should be implemented for handling `.` and `..` domains if a base is known (this would partially fix unit tests)?

I've prepared a branch/PR with this change. It doesn't contain much changes because the questions need answering first. It currently obviously fails due to these unit tests. Here it is: #555

[url-spec]: https://url.spec.whatwg.org/

**Comment by SimonSapin** [comment]
I haven’t looked the `"http://\""` case specifically, but I’ll try to answer your direct questions.



> * Is my assumption correct, is `"http://\""` incorrect?

It really depends how exactly you define “incorrect”.

> * Should `Url::parse(...)` fail, for input not conform the [URL specification](https://url.spec.whatwg.org/)?

The WHATWG URL specification has, separately:

* A concept of [valid URL string](https://url.spec.whatwg.org/#valid-url-string), designating a set of Unicode strings defined as a pseudo-grammar written in English
* A [basic URL parser](https://url.spec.whatwg.org/#concept-basic-url-parser) algorithm, defined as pseudo-code written in English. This algorithm take an Unicode string and *returns* either a URL object or “failure”. The `Url::parse` function of this crate implements that algorithm and returns `Result<Url, ParseError>`, where `ParseError` represents “failure”.

  The parser may also *emit* any number of [validation errors](https://url.spec.whatwg.org/#validation-error), even when it does not return “failure”. This crate implements `ParseOptions::syntax_violation_callback` as a way to see those. (Validation errors used to be called syntax violations in a previous version of the spec.)

https://url.spec.whatwg.org/#urls also states:

> A *valid URL string* defines what input would not trigger a *validation error* or *failure* when given to the *URL parser*. I.e., input that would be considered conforming or valid.

However I don’t know if this is accurate. That is, is there no Unicode string that matches the grammar but for which the algorithm emits a validation error or returns failure? Or, is there no Unicode string that doesn’t match the grammar but for which the algorithm returns a URL record and does not emit any validation error? This may be worth filing a spec issue. Even if this statement is accurate right now, it is rather fragile in the face of future spec changes.

Also note that the parsing algorithm takes a base URL as an optional additional parameter, but the “valid URL string” concept is defined as independent of the presence or contents of that base URL.

> * Should hostnames be limited to ASCII and IDNA characters?

Limited in order to fit what definition?

> * Are the linked unit tests faulty, based on the above?

`urltestdata.json` comes from https://github.com/web-platform-tests/wpt/tree/master/url, which is developed together with the spec. However our copy of it (and our implementation of the algorithm) is out of date and known not to match the current spec.

**Comment by timvisee** [comment]
I'm sorry, but I did not (and don't) have any time to further look into this. Thank you for your extensive answer though.

I'll close this for now, but might reopen it in the future if I've something more concrete.
