### ISSUE TITLE
Punycode 63 character limit should be enforced elsewhere

### ISSUE THREAD

**Issue by rendaw** [servo/rust-url#558]
Currently the Punycode encode method returns None if the input string is >63 characters.  Specification-wise this limitation is imposed on IDNA rather than Punycode itself, and having the restriction in `encode` prevents the use of the Punycode encode method in other contexts (ex: escaping text for header values).

I'm not sure how much this part of the method contract is relied on elsewhere, but perhaps a new `encode_unrestricted` method or something would be an acceptable solution if the interface is difficult to change at this time.

**Comment by SimonSapin** [comment]
> Currently the Punycode encode method returns None if the input string is >63 characters. 

It’s been a while since I last looked at it, but I don’t see an artificial restriction to 63 characters in [`punycode.rs`](https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/idna/src/punycode.rs). There are however comments about returning an error integer overflow, which is known not to happen in IDNA. That doesn’t mean that 64 characters will cause an error. https://tools.ietf.org/html/rfc3492#section-6.4 says that 26 bits are enough for IDNA, and this implementation uses `u32`. So the limit is probably higher than 63 (and might depend on the code point values of the characters used).

Using `u64` in the algorithm could increase the limit for some runtime cost, but there would still be a limit. Supporting unbounded input length would require something like https://crates.io/crates/bigint, which would have significant runtime cost.

> the use of the Punycode encode method in other contexts (ex: escaping text for header values)

Are those headers bounded in length? If not, Punycode may not be a good choice by the nature of the algorithm.

**Comment by rendaw** [comment]
I'm sorry, you're totally right.  I misread the comment and really didn't look closely enough at the code, my apologies.  Thank you for your polite response.  I'll close this now.

> Are those headers bounded in length?

In my case effectively yes, the specification requires transmitting error messages by header and multiple error messages might be concatenated but that would be limited and the length of each message is unlikely to be long enough to cause integer overflow when summed.
