### ISSUE TITLE
Extra JS compliant constant in percent_encoding?

### ISSUE THREAD

**Issue by SRGOM** [servo/rust-url#559]
Didn't know I'd end up here when looking at percent encoding crate but wou7ld you guys be okay with me adding an extra constant to https://docs.rs/percent-encoding/2.1.0/src/percent_encoding/lib.rs.html#129-162 
as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#Description which is compliant with JS? JS special case because it's obviously *the* first class citizen in Web.

**Comment by SimonSapin** [comment]
There are a large number of percent-encoded sets for various use cases, defined in various places. Version 1.x of this crate included some of them, but users kept asking to add more. So it is a deliberate design decision in version 2.x to only provide `CONTROLS` and `NON_ALPHANUMERIC`, with the expectation that each users should look up relevant specifications for what they’re doing and define a constant themselves.

What do you want to use this for? Are you implementing a JavaScript engine?

Please note that although MDN is a great resource, it is documentation and not a specification. If you’re implementing an API (rather than learning how to use it), please read the normative specification for it. MDN usually has links near the bottom, like in this case to https://www.ecma-international.org/ecma-262/5.1/#sec-15.1.3.3

**Comment by SRGOM** [comment]
You're obviously orders of magnitude more experienced than me so if my earlier argument of js specific URL encoding didn't appeal to you, I'm guessing you've made a conscious decision. 

My use case was- I get data from somewhere, now I have to urlencode it and pass it to a webpage so that js can decode it. So compatibility with JS is required.
