### ISSUE TITLE
Wrong parsing of smtp.office365.com:587

### ISSUE THREAD

**Issue by Weasy666** [servo/rust-url#565]
Ok...i'm not exaclty sure if this wrong or intended, but when you run this code
``` rust
let server = Url::parse("smtp.office365.com:587").unwrap();
println!("Scheme: {:?}", server.scheme());
println!("Host: {:?}", server.host_str());
println!("Port: {:?}", server.port());
println!("Path: {:?}", server.path());
println!("Query: {:?}", server.query());
println!("Fragment: {:?}", server.fragment());
println!("Domain: {:?}", server.domain());
```
you get an output that looks like this
```
Scheme: "smtp.office365.com"
Host: None
Port: None
Path: "587"
Query: None
Fragment: None
Domain: None
```

And to me it looks wrong to parse `smtp.office365.com` as a scheme and `587` as path instead of port. I'm using version `2.1.0`

**Comment by tmccombs** [comment]
I'm pretty sure that is expected behavior. To get what you expect you would need to supply a scheme, for example: "smtp://smtp.office364.com:587"

**Comment by SimonSapin** [comment]
What `Url::parse` does is parse an input string into an URL. It does so without a “base URL” that would be used as a reference in case the input is relative like `../foo.html`, so it can only parse an absolute URL.

An URL always has a *scheme* that indicates the communication protocol that ought to be used to access it. When parsing an absolute URL from a string, the scheme is expected to be at the start of the input and followed by `:`. This library and the standard it implements are designed to support unknown schemes. This allows anyone who comes up with a new protocol or combination of existing of protocols to pick a scheme string to represent it, without modifying the URL parser. `Scheme: "smtp.office365.com"` only looks wrong because of our prior knowledge of the SMTP protocol and the `.com` TLD. To this library, it is as the position in the input string where a scheme is expected.

If you want to make a URL that conveys the intended information, it should be something like `smtp://smtp.office365.com:587`. This could be useful in some hypothetical software that supports multiple email delivery protocols and wants to take a single string URL as configuration.

But it looks like what you have here and what you want is simply not an URL, it’s a host name and port number pair. The standard library has some support for this, although it is tied up with resolving host name to an IP addresses:

```rust
use std::net::ToSocketAddrs;

fn main() {
    for addr in "smtp.office365.com:587".to_socket_addrs().unwrap(){
        println!("{}\t{}", addr.ip(), addr.port());
    }
}
```
```
2603:1026:100::2	587
2603:1026:100:17::2	587
2603:1026:101:1::2	587
40.101.137.50	587
40.101.136.2	587
40.101.136.18	587
40.101.137.2	587
```

**Comment by Weasy666** [comment]
Hm...ok, i see what you mean. For me it was just strange that all of the address was parsed as scheme without an error. But it kinda makes sense when you are looking for the first `:` and assume that everything before it is part of an unknown scheme. Is the scheme limited in size?

**Comment by SimonSapin** [comment]
Per the algorithm starting it https://url.spec.whatwg.org/#scheme-start-state the scheme needs to be made of by one ASCII letter, followed by any number of ASCII letters, digits, `+`, `-`, or `.`. There is no size limit other than running out of memory, or in this implementation something close to `u32::MAX`.

**Comment by Weasy666** [comment]
Ok, thx for the info. Then i'll close this issue.
