### ISSUE TITLE
implementation question: percent encoding

### ISSUE THREAD

**Issue by ggriffiniii** [servo/rust-url#582]
This is not really an issue, but more of a curiosity that I'm hoping somebody might take the time to explain as I'm trying to learn some of the more subtle details of rust. Feel free to close the issue if you don't have the time to explain.

I'm curious why the percent_encoding crate offers these two functions, rather than a single function that is generic over anything that is AsRef<[u8]>. i.e. why this:

```rust
pub fn utf8_percent_encode<'a>(input: &'a str, ascii_set: &'static AsciiSet) -> PercentEncode<'a>;

pub fn percent_encode<'a>(input: &'a [u8], ascii_set: &'static AsciiSet) -> PercentEncode<'a>;
```

rather than this:

```rust
pub fn percent_encode<'a, T>(input: &'a T, ascii_set: &'static AsciiSet) -> PercentEncode<'a>
where
  T: AsRef<[u8]> + ?Sized;
```

The generic option is what I naturally expected, but I'm curious if there's a reason to provide two differently named functions when one could suffice. Is it somehow compile time related? Was it just because it seemed beneficial to users to have an obvious one that accepted strings? Are there other considerations I'm not thinking of?

**Comment by SimonSapin** [comment]
In short this is a choice to push users to think about character encodings, because these two function have a different semantic meaning.

Rust’s `String` and `str` types have a meaning which is that of a Unicode string. Is is different from a byte string, in the same way that the color orange is different from the number four. You can map colors to numbers for example with 24-bit sRGB, but that’s only one of many ways to do this. Similarly Unicode strings can be *encoded* into bytes or *decoded* from bytes, but doing so require choosing one character encoding among the many encodings that exist in the world.

Now of course, when you peel away enough layers of abstraction all computer RAM is made of bytes. So `String` and `str` have a memory representation based on bytes, which in Rust happens to be the UTF-8 encoding. They have an `as_bytes` method, which although it compiles to a no-op in untyped machine code is semantically doing a conversion: this method *encodes* the string to bytes, using the UTF-8 encoding. But depending on what you’re doing, maybe a different encoding such as GBK or UTF-16BE is what you really need. (UTF-8 is becoming increasingly common, but legacy systems will haunt us forever.) So maybe this method should have been named `as_utf8`. For this same reason, I think it’s questionable that `impl AsRef<[u8]> for str` even exists in the first place. But because of Rust’s stability promise it’s here to stay.

Similarly, the *pencent-encode* operation semantically takes bytes as its input. If you have a Unicode string, you first need to choose a character encoding to convert it bytes before you can percent-encode. The `utf8_percent_encode` function is a convenience for doing that with the UTF-8 encoding. But depending on what you’re doing, maybe a different encoding such as ISO-8859-2 or Shift-JIS is what you really need.

**Comment by ggriffiniii** [comment]
Thanks for taking the time to respond. Trying to encourage thinking about character encoding didn't occur to me as a reason so I'm glad to know.

Just to hear one users perspective (and take it with the appropriate grain of salt) I found the utf8_percent_encode name confusing. It took a &str which is implicitly utf8 so it didn't make sense why it would need to claim utf8 again in the function name. Just looking at the function signatures I assumed it must be doing something more than I wanted which was just to encode the underlying representation of the string, which I already understand to be utf8. Fortunately, looking at the implementation it was very clear that wasn't the case, but then of course I wondered why it would be presented in such a confusing way when something that just takes a slice of bytes is the natural interface. `impl AsRef<[u8]> for str` is obviously a utf8 conversion as you state because rust holds strings in that encoding and states it obviously.

again, thanks for the explanation.

**Comment by SimonSapin** [comment]
The name is taken from the previous name of https://url.spec.whatwg.org/#string-percent-decode

>  It took a &str which is implicitly utf8

This is the same argument for `str::as_bytes` not being named `as_utf8`. I understand where it comes from but I don’t completely agree. I think it’s useful to thing of `String` and `str` as fundamentally Unicode, and UTF-8 is "just" an implementation detail of their memory representation.

**Comment by ggriffiniii** [comment]
> This is the same argument for `str::as_bytes` not being named `as_utf8`. I understand where it comes from but I don’t completely agree. I think it’s useful to thing of `String` and `str` as fundamentally Unicode, and UTF-8 is "just" an implementation detail of their memory representation.

Yeah, I guess this is the mindset difference that created the impedance mismatch for us. I may even agree with you that if I were designing a language that it makes sense for strings to be unicode sequences with no documented memory encoding, but that's not really relevant to a rust library. As you already pointed out Strings are prominently documented as utf8, will never change away from utf8, and I would argue anyone working with rust needs to be aware of that to some degree already.

But I understand where you're coming from.
