### ISSUE TITLE
Opt-in feature flag to support the W3C standard

### ISSUE THREAD

**Issue by aledomu** [servo/rust-url#598]
The standard this crate is based on accepts some weird quirks, like hexadecimal and octal based literals in the IP address for hosts. While that might be useful in some cases, in others where defining a new protocol that uses URLs based on the W3C standard (see RFC 3986) which only accepts decimal literals, and AFAIK is less ambiguous in general, it might cause some problems.

**Comment by SimonSapin** [comment]
W3C does not have a specification for URLs. The closest is https://www.w3.org/TR/url/ , which used to be a copy / snapshot of https://url.spec.whatwg.org/ republished there for administrative reasons. It has been retracted since.

RFC 3986 is publish by the IETF and has no relationship with W3C.

Implementing IETF RFCs has been a non-goal for rust-url. Issues more specific than "might cause some problems" can be discussed on a case-by-case basis.

As to being less ambiguous, that is not my experience. IETF RFCs tend to specify grammars but leave it as an exercise to readers to decide what implementation should do when encountering inputs that do not match. This can lead to interoperability issues. https://url.spec.whatwg.org/ on the other hand has well-defined error handling.

**Comment by aledomu** [comment]
The specific use case is that I'm wary that using IP adresses as hostnames in Matrix, where each number is only interpreted as decimal numbers by its standard, might give differing results in cases like "08.08.08.08", where some servers might take it as "8.8.8.8" while this crate would error by thinking it's octal notation.

**Comment by SimonSapin** [comment]
For what it’s worth the URL parser doesn’t error when the IPv4 parser does, but considers the host name to be a domain name:

```rust
fn main() {
    dbg!(url::Url::parse("https://08.08.08.08/").unwrap().host());
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e612eed43af78f83a69f0461b31cf0a))

```
[src/main.rs:2] url::Url::parse("https://08.08.08.08/").unwrap().host() = Some(
    Domain(
        "08.08.08.08",
    ),
)
```

**Comment by tmccombs** [comment]
which would then probably result in an error later in the program when it tries to perform DNS resolution for "08.08.08.08".

**Comment by aledomu** [comment]
Seeing this is mostly a non-concern, I'll close this.
