### ISSUE TITLE
url::Url::parse fails due to a slash in password

### ISSUE THREAD

**Issue by p-alik** [servo/rust-url#640]
I hope I didn't anything wrong by referring the author of the issue https://github.com/diesel-rs/diesel/issues/2493 to url crate.

`url::Url::parse` returns `Err("invalid port number")` for the url ` "mysql://user:abc/BDE@127.0.0.1:3306/db"`.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94c2551776efb8503aa5514743170121

**Comment by valenting** [comment]
That's because according to the [URL Standard](https://url.spec.whatwg.org/) that's not a valid URL.
The slash in the password marks the beginning of the path, so it assumes user is the host, and abc is the port. Since the abc doesn't parse as a number, it is an invalid port, so parsing fails.
To make it work you either have to escape the slash - parsing `mysql://user:abc%2FBDE@127.0.0.1:3306/db` works - or parse `mysql://127.0.0.1:3306/db` and set the user and password afterwards, like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94c2551776efb8503aa5514743170121)
