### ISSUE TITLE
Constructor

### ISSUE THREAD

**Issue by 89z** [servo/rust-url#672]
I just noticed, that it seems this crate does not have a proper constructor for the `Url` object. I found these:

- https://docs.rs/url/latest/url/struct.Url.html#method.from_directory_path
- https://docs.rs/url/latest/url/struct.Url.html#method.from_file_path
- https://docs.rs/url/latest/url/struct.Url.html#method.join
- https://docs.rs/url/latest/url/struct.Url.html#method.parse
- https://docs.rs/url/latest/url/struct.Url.html#method.parse_with_params

but none of those allow you to build a `Url` from the individual parts. Something like this:

~~~rust
let url = Url::new("http", "example.net");
~~~

Or similar to other crates, where you build an object from the separate parts:

~~~rust
use chrono::{Utc, TimeZone};
assert_eq!(Utc.ymd(2015, 5, 15).to_string(), "2015-05-15UTC");
~~~

https://docs.rs/chrono/latest/chrono/offset/trait.TimeZone.html#method.ymd

**Comment by valenting** [comment]
The [URL Spec](url.spec.whatwg.org/) doesn't have an algorithm for building a URL from parts.
There was https://github.com/whatwg/url/issues/354 opened with a similar use case, but it didn't seem to go anywhere.

**Comment by 89z** [comment]
That is not true at all:

> Parsed URI components can be recomposed to obtain the corresponding URI
> reference string.

https://tools.ietf.org/html/rfc3986#section-5.3

**Comment by valenting** [comment]
> That is not true at all:
> 
> > Parsed URI components can be recomposed to obtain the corresponding URI
> > reference string.
> 
> https://tools.ietf.org/html/rfc3986#section-5.3

This crate implements the URL spec, not rfc3986.
But there's nothing stopping you from implementing a crate that implements section-5.3 and passes it to Url::parse 🤷

**Comment by 89z** [comment]
I guess you are choosing to be intentionally thick? RFC 3986 is part of the
base URL standard:

https://en.wikipedia.org/wiki/URL

IE, the standard on which all other standards are based, including the "living
standard" you seem to be referring to. So if you want to ignore that, its your
business, but dont pretend to have a full implementation of the URL/URI standard
with this crate, because that not what we have here.

**Comment by djc** [comment]
Again, this crate implements the *WHATWG* URL standard, not any of the IETF RFCs.

**Comment by 89z** [comment]
Ok fine, did neither of you see this section?

https://url.spec.whatwg.org/#url-serializing

**Comment by 89z** [comment]
I see my comment was marked as disruptive, so clearly my input is not welcome.

I will just make one final comment. I made this issue in good faith, and I was
@valenting just closed it flippantly, much like he did my other issue. That is
not a way to promote discussion. But perhaps you all dont wish to promote
discussion. But if thats the case, maybe just disabling issues would be better.

I made a good faith effort in my case, citing two standards that define
constructing URLs from parts, AKA serialising:

- https://tools.ietf.org/html/rfc3986#section-5.3
- https://url.spec.whatwg.org#url-serializing

and no counter has been made to that. If it just something you dont want to
implement, fine, just say that. But to sit there and pretend that its something
that not defined by the standards, is strange to say the least.

**Comment by valenting** [comment]
Good faith discussion is always welcome, disrespectful comments are not.

>     * https://url.spec.whatwg.org#url-serializing

This section details serialization - which you get by calling `into_string()`

So far I haven't seen a use case where such a construction API is necessary and needs to be implemented in the rust-url crate.
I'd be happy to reopen the issue when such a use case is presented. Cheers!

**Comment by andrewbaxter** [comment]
I just got here after performing a similar search. I don't want to parse a string since there's increased risk of encoding/decoding errors in the round trip (loses type safety as a string), plus it's unnecessary computation.

I'm using Reqwest so I don't have a choice but to use this repo's URLs.

> The [URL Spec](https://url.spec.whatwg.org/) doesn't have an algorithm for building a URL from parts.

I don't think the discussion was particularly verbose on either side, but the `url-serializing` section of the WhatWG spec seems to describe exactly building a url string from component parts.  This was the initial objection AFAICT, and it seems that @89z's comment addressed this directly. Are there other objections to this feature?

I'm not super familiar with web standards, and it's not said explicitly here, but I'd _guess_ the worry is that there's information in a URL string that's not present in just the components of the URL struct which prevents guaranteed identical reproduction.  From my perspective and general use this isn't an issue, and in fact canonicalization by reproduction from components is something I've used before.

The current implementation stores both the original string and the components, side by side I think.  There's code that manipulates both together, but not any that builds the string from scratch (? if my light reading's correct) so perhaps this would take a significant amount of effort.

Is this roughly an accurate description of things? Or was there some other unstated subtlety? Is there some servo use case that requires exact reproduction?

FWIW both the Java and Python url libraries both provide this functionality, and the Python library claims to support the WhatWG spec in some fashion.

**Comment by 89z** [comment]
@andrewbaxter all you need to know, is right here:

> So far I haven't seen a use case where such a construction API is necessary and needs to be implemented in the rust-url crate. I'd be happy to reopen the issue when such a use case is presented. Cheers!

This is them backtracking, in so many words. Its them saying essentially:

> OK fine you're right, it is defined in the standard(s), but we don't find that case useful. Prove to us that it is.

Thats not really a discussion I have any interest in having. To me, dealing with any serialization has two parts:

1. De serializing a string into a structure
2. Serializing a structure into a string

From where I sit, the maintainers here implemented step one, looked at step two, and said "nope, we aren't going to implement that". Given the hostile previous comments (and the projection of "disrespect"), I would advise asking Reqwest to switch URL crates, or perhaps seek out another HTTP crate. Here are some that might be worth looking at:

- attohttpc
- oxhttp
- ureq

**Comment by tmccombs** [comment]
> I would advise asking Reqwest to switch URL crates

To what? I'm not aware of any suitable crate, and a quick search for other url crates didn't turn up anything interesting.

> or perhaps seek out another HTTP crate

Even if another crate was suitable for replacing reqwest, which depending on the use case may or may not be the case, and the cost of switching to a different library was not too high, none of those http client libraries really solve the problem. oxhttp and ureq just accept strings as the url, and attohttpc's Url struct doesn't have a constructor API either.

**Comment by 89z** [comment]
> To what? I'm not aware of any suitable crate,

I think these do the trick, but I haven't looked at it in some months:

- oni-comb-uri-rs
- uriparse
- url-parse

Im sure you will be happy to point out whats wrong with them, so I will leave that to you.

> and a quick search for other url crates didn't turn up anything interesting.

I wont blame you for this one, search is not good on crates.io [1], assuming thats what you used.

> none of those http client libraries really solve the problem. oxhttp and ureq just accept strings as the url, and attohttpc's Url struct doesn't have a constructor API either.

Fair point. However I don't wish to argue against that, as my original posted issue was specific to the `url` crate, not any HTTP crates. Ideally some other HTTP crate is out there, that accepts a URL constructor instead of a string.

1. https://github.com/rust-lang/crates.io/issues/5222
