### ISSUE TITLE
Panic on setting hostname for `non-spec:/.//p` URL

### ISSUE THREAD

**Issue by CYBAI** [servo/rust-url#700]
While trying to investigate https://github.com/servo/servo/issues/28386, I found this test case for `hostname` setter will crash in Servo

```json
{
    "href": "non-spec:/.//p",
    "new_value": "",
    "expected": {
        "href": "non-spec:////p",
        "host": "",
        "hostname": "",
        "pathname": "//p"
    }
}
```

I can reproduce this issue in `rust-url` with adding this test case to the `url/tests/setters_tests.json` in the `hostname` section.

```
---- setters_tests stdout ----
    test: "non-spec:/.//p".hostname = ""
  failed: invariants checked -> "9 != 11 (self.username_end != self.scheme_end + 3) for URL \"non-spec://p\""
```

**Comment by sanchayanghosh** [comment]
Sure. I see there are no fixes yet. I'll work on the issue.

**Comment by sanchayanghosh** [comment]
The issue here is with the test case. However, this needs to be clarified further. Since, this test fails the self test cases that you ran. Here, once this url is parsed, it becomes

`non-spec://p`. This way, the url becomes a URL with a hostname and hence, changes its form.

Eg. non-spec:/./localhost/someotherfoler becomes: 

non-spec://localhost/someotherfolder, which literally changes what the URL stands for if we parse a second time as the test case data.rs under URL does.

1. The URL specifications mention, that . in pathname are to be dropped as done by the program. So, instead of dropping them we retain them.
2. We do not parse URLs as strings the second time, instead treating them directly as tokens. And only use a special to_url function that will insert the characters the same way they were input.

**Comment by sanchayanghosh** [comment]
This would need clarification based on the URL specification. Reason being that, 

typically double slashes are not allowed if the URL does not contain an authority component. However, the same on entry is still allowed in browsers. The clarification that is needed is how the rust-url should parse this. Should it remove any double slashes it encounters, effectively making: 

`non-spec:/.//p` => `non-spec:/p` as it would have done for `non-spec:/./p`

or should it retain a single slash, like `non-spec://p`, but ends up changing the format of the URL to one having a domain name and path, thereby changing the structure of the URL.

eg. `non-spec:/.//localhost/thispath` would become `non-spec://localhost/thispath` to illustrate the quandary. 
If the latter is true, then the test case failing is due to the self parsing tests that will fail.

**Comment by valenting** [comment]
Fixed by https://github.com/servo/rust-url/pull/817
