### ISSUE TITLE
DB_URL Password complexity is not supported. For example, the password is QAZwsx123@#

### ISSUE THREAD

**Issue by songlinshu** [servo/rust-url#805]
Password complexity is not supported. For example, the password is QAZwsx123@#
![image](https://user-images.githubusercontent.com/45619496/202838515-2c505d1c-7eae-4bbf-84ed-8dab1876a86d.png)
![image](https://user-images.githubusercontent.com/45619496/202838577-0f42e775-ef37-434c-a095-dd70f4806659.png)

**Describe the bug**
A clear and concise description of what the bug is. Include code snippets if possible.

**Comment by valenting** [comment]
That's because the password is invalid.
https://jsdom.github.io/whatwg-url/#url=bXlzcWw6Ly9zYTpRQVp3c3gxMjMhQCNAMTI3LjAuMC4xOjE0MzMv&base=YWJvdXQ6Ymxhbms=

That's because URL parsers assume the userInfo stops at the first `@` and then fails parsing the host because it contains `#@`.
[Special characters](https://url.spec.whatwg.org/#userinfo-percent-encode-set) in the username or password need to be percent encoded.

You can see this working in the small [demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=30f63968c3a5da51c606dcf55e097f8a)

**Comment by songlinshu** [comment]
Thank you!
