### ISSUE TITLE
Wrongly resolves ip to domain.

### ISSUE THREAD

**Issue by mokeyish** [servo/rust-url#828]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
A clear and concise description of what the bug is. Include code snippets if possible.

Input： `udp://8.8.8.8:53`

Output: `Host::Domain("8.8.8.8")`

Expect: `Host:Ipv4(8.8.8.8)`

**Comment by valenting** [comment]
This behaviour is caused by the fact that udp is a non-special scheme. So it could have basically anything in the hostname.
For example [udp://555.555.555.555:53/](https://jsdom.github.io/whatwg-url/#url=dWRwOi8vNTU1LjU1NS41NTUuNTU1OjUzLw==&base=YWJvdXQ6Ymxhbms=) is a valid URL, but you wouldn't expect it's hostname to be an IP, right? It's an opaque domain.

**Comment by mokeyish** [comment]
Can we have an option to configure udp to a special schema?
