### ISSUE TITLE
Incorrect error when url contains number sign

### ISSUE THREAD

**Issue by agirorn** [servo/rust-url#922]
When I parse url with an invalid character like the # sign in the password part of the url I get `Err(InvalidPort)` error but I think I should be getting a more helpful error like InvalidPassword for instance

```rust
    let parsed = Url::parse("postgres://user:pa#ss@host:9999/database");
    println!("{:#?}", parsed);
```

```shell
Err(
    InvalidPort,
)
```

**Comment by valenting** [comment]
The error is actually correct. Because the # is present in the password, the user is now parsed as a host, while pa is parsed as a port and fails. If you change the URL to `postgres://user:12#ss...` it will parse.

Check out the reference URL parser [here](https://jsdom.github.io/whatwg-url/#url=cG9zdGdyZXM6Ly91c2VyOjEyI3NzQGhvc3Q6OTk5OS9kYXRhYmFzZQ==&base=YWJvdXQ6Ymxhbms=)
